name: MitalPatelPhoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a12'
    - '#fae0e6'
    - '#3e4e6c'
    - '#8080a3'
    - '#de4659'
  brandStrength: 0.30423355428501964
  lightness: 0.2452910258434713
  saturation: 0.17826456390321255
  rhythmicContrast: 0.2886367766186595
purpose: []
